################################
# GENERAL CONFIGURATION
################################
language: python
dist: trusty
# We are going to need a full-VM to run docker containers inside.
sudo: enabled
# Vdist needs docker enabled to work.
services:
- docker


################################
# TEST MATRIX
################################
python:
- 2.7
- 3.6
- nightly
env:
 global:
 - secure: "Ig3i1GxGTxz+J1LR46cmkkWzpHBUsUVpTVJZ5nyrH6781eoQmZStNfBdmn32MogumbyTnQzUEtWHEdAMErwtmOcCOo0LkrHKYNlJopVA06NwO7+IO8FGpSEydeMYFMsWdEO8Hg2vk/xr+K7UjVcJvG0usPxpEpIE17abif64mnDJXuB3VHchi/0I1BYimnmXVVFh93A+xOdXxbYjnPCDSQQ+f85NqTyMw1aTCkYuqG1XOZBdrO0rGd8McHjdbwLFOmN0Ve6SaollosztA/AgI5VcfsCn4tlSpg6DmY976QWkWchVVQI33vJEYGXiA4VFLzfGJsobQQZHuAieLBsvgj3Lz8OVVItnIPYVOcJ1qDbQP09VZKxFo9zDajJq1169oYSFlOj/0KrHJYEIGHwk+kwBWn6THdnadY8qeko1TEdWfrsgn3gmCUK9njQCA5UJM+7dPTWTE++fSBc0dZqXLV8ooPJ7ZjCMX7BCG0PR9Sr2PRLwOFtGYpWzdu4hIM8r8TBLZfo85LcGwa+mhOtfD+bdxCoYyvsmQzgGpcVWqJc76WuvemHSjmpV08mKu3UHyRPrmUP2yrD700u05kj9G6mpu0ZGzQgq567YaUy/jaQp2esNNhZ4PNdDvKtatUDY7OQ9RXguNKSYNI+b+7IgDdK3vQ4uCBMjDP4F1VEulJ0="
 matrix:
  - TEST_TAG="test_generate_deb"
  - TEST_TAG="centos6"
  - TEST_TAG="centos7"
matrix:
  allow_failures:
  # Actually I only build with latest stable python release, but I want
  # to be aware in advance if any dev python version is going to crash
  # my future builds.
  - python: nightly


################################
# BRANCH FILTER
################################
branches:
  only:
  - staging


################################
# RESULT NOTIFICATIONS
################################
notifications:
  recipients:
  - dante.signal31@gmail.com
  on_sucess: always
  on_failure: always


################################
# TESTING
################################
before_install:
  - sudo apt-get update -qq
  # To test we need docker.io but that comes already packaged in travis image
  # so we don't need to install it.
  - sudo apt-get install -qq libssl1.0.0 rpm
install:
  - pip install -r requirements.txt
script:
  # Seems that centos7 tests fail if I don't give them additional time.
  - if [[ $TEST_TAG = "centos7" ]]; then travis_wait 30 pytest -v -rs -k $TEST_TAG; else pytest -v -rs -k $TEST_TAG; fi
#  - echo "Dummy test"



################################
# DEPLOYMENT
################################
jobs:
  include:
  # Update master branch.
  - stage: Branch merge to production branch
    python: 3.6
    if: branch = staging
    script:
    - ci_scripts/merge_with_production
  # Upload packages to Python Package Index.
  - stage: Pypi deployment
    python: 3.6
    script: echo "Deploying to Python Package Index..."
    deploy:
    - provider: pypi
      user:
        secure: "DUgDI1bayvA2uPQRck4jT9GEiRLgGjh+zSZVqZrdO7rR8LG3JDdsuGxYUOyvoH498q4uUY6a4VoN+VcxOHyDbXkMSEz91P29rj5lKAnyk3X0+iI81HyF42BMvOB4BzNpn5ym9LWmPpijDX09NRC50EvqMZTWxOabvOmmbLRoc21h2pPce+4Qs6YK6p3QSKVKRXISRMmH6VoSSSO1dMFDvF8NKt+H4v8SFsBdQae5VFd4/srHlBH2cF1Atow/Y3SPtqG3Y4Ln40noTowgO0Sh2Gry/6ioGeURaYGLWdKPyvHuLQTqR8GOkzvlkbY0gSjTkCVDzoqfLepDwJW0x8sw37LE/4HB18YxhT/d3IHPgESU2wttVeNA3/RHGOy/aXJDQrs81lPIZyJHNmBaJJpkvV6jRct80c0xSaWiH5X/DomLpxKpf5e+Itca5sCV5rwnf31AW05B2sdoEq6UxQMeoNJ5o5+3yM8H9HWwfZ88sSgcgqENnye6QxDPIMXGgXyMZ7qiuFhucsxbQ8SqMetAtc/yq08szuFVqGuSkRBGbPpP/QgebY885TdKsGCCUUNf1YmzNksYRaDvmPGizpxYPPgkSqehIAocVYC8WPwHYe4yio25UVFbt/QixSiBEOx1+G8Qb/OY/Hqpn4rZsqmuYUgzfxtUm5LzGXG565dI7dE="
      password:
        secure: "X7LVEIqj77L8N8ZRY4rPyQunL44GqnzwCdvXF8n03OUIC+U4WVC5QXMdcZ8PnJBJHxI1jQuascZGBT4+xO97sMWlCFZxHGLDkWTJkp3fqxIaO5BjpGEl3Ofl1qAHMhchknRdko18bFiE6sm/PLbg66rspBlepSGsGLf/3j9DIMIx9voWD5VnspBFLnhMEUmtyjrk+ORIR0O7mXPrgEkyZGdGRly4Tuo8jTg0v7LbskkkNDJDYtwfiGLkDSK0+5TuMiLuzo4Zf3pe2+clTvqzN+xx/2mW5w46/bYNNTqoFRPwN3X2MGCddnR07Njo4XHTaI+6gXh1/Dwax5Q/zsf8IrSNS9yBbco5eQx/0FlZuVzIFxPsWJbd90V0a5914zP3U3rJoWMULCje/dBW06atDEvCojMOXBiLmtAd3kbXdifrzcO+CPjBI8SaBaSRC48szRUeIoRkSKLzGz/c/wehU7BfV/8UQZ4ds+XCYfnKCzA66pzwOnSOXeRnV3EJAcugZhpY6trohKzFZxEECBhYu3DZXV49vZChWtKWUoc+WznDAR36wFlvOLMA4eZV4CVgSnNnqd26iaSLOYGNDbT956Z98mzV4MmAAuqAlaEWoj12c5qWOBd9N2wayCKd1YsPbZ+sdBwPht5MKJy8Nf61zF3LgABXndY0pITSdxEkRk0="
      distributions: "sdist bdist_wheel"
      on:
        branch: staging
  # Build DEB and RPM packages and upload them to Github and Bintray.
  - stage: System packages deployment
    python: 3.6
    if: branch = staging
    script:
    - travis_wait 20 sudo ci_scripts/build_system_packages
    - ci_scripts/tag_release
    - ci_scripts/create_bintray_descriptors_from_templates
    deploy:
    # Github Releases.
    - provider: releases
      api_key:
        secure: "B+nKpJMdEL2F6Ly6zH/6D3iuHNVodJpFa6nDsUMGOJAOVlJFjuZA6+natEMm7QZudZYFxyhidil86UsKtyM0qEP9LzzF3861npLCeD6FQrmLJabj5TxfLldE1W7ZEXLr2tSWkysN3y3pGKSWZMQa74vfvo7PI6y02afJ9B3OQfDJx9jpwvFiXHwTLtkXzKR/P+WvjAvb/HrETjnaYhy5a7GSAXQPI6dtheGUiPUIaozJJS6sSX+h5Ro4FCwNilQM86vs1vLJpcjtMPssVwBM41fHhxqJxLI1QAivqHXCuR0TLdx6AyRYRG5Fcgyyok2WTXgzTRwA/n27PnkaPQOhKiyChR0kZs2jpQ/U+gf2QEElbQlRRLkEWNSV3s8TpOVSs+vWmDb/AI/HUYtbiJTZCclo+jh+S4bOkqWbbdhOauI5xdrYlopRWRwT7FbYqNONor0jSMsLnhGUMOXEsq0v6f2FoCKQBFgSjddoztLBkqa8PqOcnn7b0yVk09UwLDNJENjD4BLK2wI5W9Z2RC0pxsf6RJ4QMBfJ8ONEm8GSytEQZDOZHkqkh79dzadNufwJ41k5XHEXLtTMRGFgOAE/fl+A6OZJUxN6l/mBh9mkdIqDoFvZZRMh5ogodh04btv45mUWQUOuOgnCOzwP46Mn/poQ19akSYh6pibsYhgAk4k="
      file_glob: true
      file: package_dist/*
      skip_cleanup: true
      on:
        all_branches: true
    # Bintray deb repository.
    - provider: bintray
      file: "packaging/vdist_deb_bintray_descriptor.json"
      user: "dante-signal31"
      key:
        secure: "BD/HMEK0BighM5+1sdJS076YAFQvBebyFKhmGnqw7L+HxjqYdWI7KJ5htbTqQVqmQw+zlKrVcukKX6eKGShIsDJzHI66t2TJwk8jQsLwEmstA9N2JhETMYC82nbgJ+YbDtT7MA4Uw5uH95UrWX4BR4hpQkOMyQGigrqdPmyeX6GacDhMMleHcv3nbfInqncPJMRzACYgL3z+RzrLU9ZNvTsvMdJvFkPMC5Q0fpUn7MISHs5/yNPpFZ13mFdraPDUX7YOEP5PUqbfSJtF/KZIMCOigqMF++qQ3m80elx87GsUVJscLg7c+7cEgL1dgQ2Dt3WU5nT0WX1a2wod9bJjFMl5ob7WmS4dL2vYtJpuar0ZdrTIAgXQe0Y/q/TTAasn164SXhDM0say5Z3CPg+TgKH4kUGKNug7xmLRGJyQyeyUw8WU93psFo0t6ADZ0c68maBPwUX7YsFqod4jRztS/Wk9VrNMA+Qe27dz5Cqr1jbGb3JWfmDLddvmyCo1R5s4zHJK8rZeq/TQvfd9zU7Tcrdin79MxvfNjm6M9RRWlix0V1de6EfK1f0TYTPai9rSsdceK2CH4Shca/tG/9AK1FZUAYG/IH/Jl8sSzQ95wFi457gIlpFyvMZhpRokI+iwQ1Vlt4KIRKHcpP4KcYKGU37dCXYOsikluKAdHVzgMV8="
      skip_cleanup: true
      on:
        all_branches: true
    # Bintray rpm repository.
    - provider: bintray
      file: "packaging/vdist_rpm_bintray_descriptor.json"
      user: "dante-signal31"
      key:
        secure: "BD/HMEK0BighM5+1sdJS076YAFQvBebyFKhmGnqw7L+HxjqYdWI7KJ5htbTqQVqmQw+zlKrVcukKX6eKGShIsDJzHI66t2TJwk8jQsLwEmstA9N2JhETMYC82nbgJ+YbDtT7MA4Uw5uH95UrWX4BR4hpQkOMyQGigrqdPmyeX6GacDhMMleHcv3nbfInqncPJMRzACYgL3z+RzrLU9ZNvTsvMdJvFkPMC5Q0fpUn7MISHs5/yNPpFZ13mFdraPDUX7YOEP5PUqbfSJtF/KZIMCOigqMF++qQ3m80elx87GsUVJscLg7c+7cEgL1dgQ2Dt3WU5nT0WX1a2wod9bJjFMl5ob7WmS4dL2vYtJpuar0ZdrTIAgXQe0Y/q/TTAasn164SXhDM0say5Z3CPg+TgKH4kUGKNug7xmLRGJyQyeyUw8WU93psFo0t6ADZ0c68maBPwUX7YsFqod4jRztS/Wk9VrNMA+Qe27dz5Cqr1jbGb3JWfmDLddvmyCo1R5s4zHJK8rZeq/TQvfd9zU7Tcrdin79MxvfNjm6M9RRWlix0V1de6EfK1f0TYTPai9rSsdceK2CH4Shca/tG/9AK1FZUAYG/IH/Jl8sSzQ95wFi457gIlpFyvMZhpRokI+iwQ1Vlt4KIRKHcpP4KcYKGU37dCXYOsikluKAdHVzgMV8="
      skip_cleanup: true
      on:
        all_branches: true
